// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-tasks.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's PrepOS tasks, optionally filtered by date (YYYY-MM-DD) and done status.",
  inputSchema: {
    date: z.string().optional().describe("Optional date filter in YYYY-MM-DD format."),
    done: z.boolean().optional().describe("Optional filter for completion status."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, done, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sbForUser(ctx).from("tasks").select("id,text,date,done,priority,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (date) q = q.eq("date", date);
    if (typeof done === "boolean") q = q.eq("done", done);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { tasks: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a new PrepOS task for the signed-in user.",
  inputSchema: {
    text: z2.string().min(1).describe("Task text."),
    date: z2.string().optional().describe("Optional date (YYYY-MM-DD); defaults to today."),
    priority: z2.enum(["low", "medium", "high"]).optional().describe("Optional priority.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ text, date, priority }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await sbForUser2(ctx).from("tasks").insert({
      user_id: ctx.getUserId(),
      text,
      date: date ?? today,
      priority: priority ?? "medium",
      done: false
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created task ${data.id}` }], structuredContent: { task: data } };
  }
});

// src/lib/mcp/tools/list-revision-items.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_revision_items_default = defineTool3({
  name: "list_revision_items",
  title: "List revision items",
  description: "List spaced-repetition revision items for the signed-in user. Optionally filter to items due on or before today.",
  inputSchema: {
    due_only: z3.boolean().optional().describe("If true, only return items with next_rev on or before today."),
    topic: z3.string().optional().describe("Optional topic filter."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ due_only, topic, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let q = sbForUser3(ctx).from("revision_items").select("id,text,topic,next_rev,rev_count,added_date").eq("user_id", ctx.getUserId()).order("next_rev", { ascending: true }).limit(limit ?? 50);
    if (due_only) q = q.lte("next_rev", today);
    if (topic) q = q.eq("topic", topic);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { items: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-study-notes.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sbForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_study_notes_default = defineTool4({
  name: "list_study_notes",
  title: "List study notes",
  description: "List the signed-in user's study notes, optionally filtered by category or search term in the title.",
  inputSchema: {
    category: z4.string().optional(),
    search: z4.string().optional().describe("Case-insensitive substring match on the title."),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sbForUser4(ctx).from("study_notes").select("id,title,category,content,date,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (category) q = q.eq("category", category);
    if (search) q = q.ilike("title", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { notes: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-study-note.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z5 } from "npm:zod@^3.25.76";
function sbForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_study_note_default = defineTool5({
  name: "create_study_note",
  title: "Create study note",
  description: "Create a study note for the signed-in user (markdown content supported).",
  inputSchema: {
    title: z5.string().min(1),
    content: z5.string().min(1).describe("Markdown-supported body of the note."),
    category: z5.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, content, category }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await sbForUser5(ctx).from("study_notes").insert({
      user_id: ctx.getUserId(),
      title,
      content,
      category: category ?? null,
      date: today
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created note ${data.id}` }], structuredContent: { note: data } };
  }
});

// src/lib/mcp/tools/list-job-applications.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z6 } from "npm:zod@^3.25.76";
function sbForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_job_applications_default = defineTool6({
  name: "list_job_applications",
  title: "List job applications",
  description: "List the signed-in user's tracked job applications, optionally filtered by status or company.",
  inputSchema: {
    status: z6.string().optional(),
    company: z6.string().optional(),
    limit: z6.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, company, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sbForUser6(ctx).from("job_applications").select("id,company,role,status,stage,applied_date,follow_up_date,location,salary,url").eq("user_id", ctx.getUserId()).order("applied_date", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (company) q = q.ilike("company", `%${company}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { applications: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qwqouxprxanokontxaxv";
var mcp_default = defineMcp({
  name: "prepos-mcp",
  title: "PrepOS",
  version: "0.1.0",
  instructions: "Tools for PrepOS \u2014 a personal AI/ML interview prep dashboard. Use these to read and update the signed-in user's tasks, revision items, study notes, and job applications.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tasks_default, create_task_default, list_revision_items_default, list_study_notes_default, create_study_note_default, list_job_applications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
